### ISSUE TITLE
Usage of string-match-p

### ISSUE THREAD

**Issue by thisch** [wyuenho/emacs-pet#13]
In https://github.com/wyuenho/emacs-pet/blob/main/pet.el#L221 you're using `string-match-p` for the config file extensions.
This doesn't work for me, because `string-match-p` returns 0 in my case. I would simply use 

```elisp 
(or (equal "yaml" ext) 
     (equal "yml" ext)
     (eq 'yaml-mode mode))
```

  or maybe you have a better idea.

```elisp
(string-match-p "ya?ml" "yaml")
0

(string-match-p "ya?ml" "yml")
0
```

**Comment by wyuenho** [comment]
Why doesn't it work for you?

**Comment by thisch** [comment]
Good question. 

What does it return for you?

```elisp
(string-match-p "ya?ml" "yaml")
(string-match-p "ya?ml" "yml")
```

BTW I'm on emacs-29

**Comment by wyuenho** [comment]
0, which is t in elisp.

**Comment by thisch** [comment]
Ok, maybe there was a misunderstanding then. I always thought that sth is fishy because `yaml-p` is 0.

**Comment by thisch** [comment]
Thx for the tip about `0` being `t` in elisp!  This ticket can be closed.
