### ISSUE TITLE
Unable to guess virtualenv

### ISSUE THREAD

**Issue by Compro-Prasad** [wyuenho/emacs-pet#16]
`pet-project-root` returns `nil` in my sample python project initialized using `poetry`. I am using Emacs 28.2 without `projectile`.

`pet-locate-dominating-file` should generally return the directory which has `pyproject.toml` but fails to do so as it is also dependent on `pet-project-root`. Removing the dependency on `pet-project-root` should help in this case.

### Source:
https://github.com/wyuenho/emacs-pet/blob/7620c18223f126c384dbf42b0b167a6066a81dd1/pet.el#L157

**Comment by wyuenho** [comment]
Just git init the directory will solve your problem.

**Comment by Compro-Prasad** [comment]
@wyuenho Technically speaking you are correct.

On the other hand I have many throw out projects where doing a `git init` is too much.

Many people who don't know about version control system and only python wont be able to make use of this package.

Thus, from a general usability standpoint you are completely wrong.

**Comment by wyuenho** [comment]
In that case, install projectile.

**Comment by Compro-Prasad** [comment]
Since you don't consider this an issue, I just copied your pet.el and
modified for my own purposes.

https://github.com/Compro-Prasad/emacs-config/blob/master/lisp/pet.el
