### ISSUE TITLE
Doesn't work on remotes over TRAMP

### ISSUE THREAD

**Issue by egelja** [wyuenho/emacs-pet#19]
But here's a patch that fixes it!

[emacs-pet-tramp.patch](https://github.com/wyuenho/emacs-pet/files/11042887/emacs-pet-tramp.patch)

**Comment by wyuenho** [comment]
Thanks for the patch! I was wondering if you mind opening a PR? It's easier to discuss this way.

**Comment by MrAwesomeRocks** [comment]
> Thanks for the patch! I was wondering if you mind opening a PR? It's easier to discuss this way.

#20
