### ISSUE TITLE
Support flymake?

### ISSUE THREAD

**Issue by publicimageltd** [wyuenho/emacs-pet#28]
**Description**

I use eglot in a virtual environment. Everything works fine except that mypy does not load the stubs for typechecking imported modules. I'm using flymake, and it reports an error that mypy cannot find the stubs. Except that the stubs are installed in the venv. 

If I switch to flycheck, the mypy error goes away. Thus I believe that flymake somehow does not fully recognize the environemt set by PET. 

If I can test this, I'd welcome some pointers how to investigate this issue. It might, of course, also be due to eglot, but I have no idea how to test it (and I do not want to install lsp-mode).

** Setup

 - PET latest version
 - Emacs 29.1 with eglot
 - Python and mypy latest version
 - Standard installation of PET, as recommended in the doc (by using `setq-locale` and the hook `python-base-mode-hook`.

**Comment by wyuenho** [comment]
Which LSP server are you using?

**Comment by publicimageltd** [comment]
[Spyder pyhon lsp](https://github.com/python-lsp/python-lsp-server) and ruff as a linter

**Comment by wyuenho** [comment]
Please tell me about your directory structure and how you normally run mypy, and what configuration you have so mypy can pick up your stubs.

**Comment by publicimageltd** [comment]
I have a `.venv` file in the python project folder. Mypy is installed globally (I'm on arch, it is installed as a pacman package). I don't run mypy manually, but delegate that to Emacs.

I just called mypy manually, same reply (no stub installed etc.). To check, I Just installed it in the activated venv (`pip install mypy`), but no change.

But as to how mypy communicates with Emacs: no idea. I thought it is done by eglot.

**Comment by wyuenho** [comment]
In this case I would suggest you play around with mypy's configuration before jumping to the conclusion of this being a bug of PET. If it doesn't run in your terminal, it's not going to run in Emacs.

**Comment by publicimageltd** [comment]
Yes, sorry for the noise. Will check on that. Thanks for the fast reply!
