### ISSUE TITLE
Manual venv selection?

### ISSUE THREAD

**Issue by sho-87** [wyuenho/emacs-pet#33]
I realize a large part of this project is to auto identify venvs, but wondering if theres a possibility of a manual mode? Where the user can provide a path to a venv directory or choose from a list of available venvs

There are times where I'm working on a single script that doesnt have all the scaffolding of an actual project, and I just want to temporarily borrow a venv from somewhere else (as it might have linters etc setup already). Or if I'm working in a project with its own venv but want to switch to another venv temporarily as it has different versions of dependencies

The closest Ive been able to find is [pyvenv](https://github.com/jorgenschaefer/pyvenv), but it doesnt change the paths for all the tools (flycheck, lsp etc)

**Comment by wyuenho** [comment]
Not currently. Firstly there's #30 and #31, secondly I'd really like to not evolve PET to any of the dozen Emacs virtualenv tools out there. PET is not a tool for your terminal, it is a tool for your Emacs buffers. 

That said, by default PET detect these [patterns](https://github.com/wyuenho/emacs-pet/blob/main/pet.el#L111) in your project. Why don't you just symlink the virtualenv in your new project and see if that works for you.
