### ISSUE TITLE
PET get stuck in recursive search on large code bases

### ISSUE THREAD

**Issue by abougouffa** [wyuenho/emacs-pet#45]
**Description**

On large code bases, or code bases with a lot of files (files used for testing for example), running Python code with `C-c C-c` causes Emacs to get stuck.

I've run 

```shell
kill -USR2 $(pidof emacs)
```

To trigger a debug, the traceback is provided below.

It seems like, when I have a lot of files inside the directory, PET get stuck while recursively searching for some `.pre-commit-config.yaml` file.

The problem goes away when I move the `tests/` directory (which contains a lot of files/directories) outside the project's root.

**Reproduction steps**

1. Place a lot of directories and files in a directory inside the project's root directory.
2. In my machine, there is 153296 directories and 1065309 files (nested);
```shell
$ cd /path/to/project
$ cd tests
$ find -type d | wc -l
153296
$ find -type f | wc -l
1065309
```
3. Open a `*.py` file from the project's root.
4. Press `C-c C-c`

**Expected behavior**

The script should run.

**PET version**

Latest: 73f9f0aedc6f333c30f71988ca1db50044999ef6

**Emacs version**

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: Bookworm

**System tools versions**
- dasel v2.7.0
- sqlite3 3.40.1
- yq 4.40.5

**Additional context**

```
Debugger entered--Lisp error: (quit)
  call-process("git" nil t nil "--no-pager" "ls-files" "-z" "-c" "--exclude-standard" "-o")
  process-file("git" nil t nil "--no-pager" "ls-files" "-z" "-c" "--exclude-standard" "-o")
  vc-do-command(#<buffer  *string-output*> 0 "git" nil "--no-pager" "ls-files" "-z" "-c" "--exclude-standard" "-o")
  vc-git-command(#<buffer  *string-output*> 0 nil "ls-files" "-z" "-c" "--exclude-standard" "-o")
  project--vc-list-files("~/work-stuff/workspace/scripts/" Git nil)
  #f(compiled-function (dir) #<bytecode 0xaa1d8a9856d78aa>)("~/work-stuff/workspace/scripts/")
  mapcan(#f(compiled-function (dir) #<bytecode 0xaa1d8a9856d78aa>) ("~/work-stuff/workspace/scripts/"))
  #f(compiled-function (project &optional dirs) #<bytecode 0xf5ba0430963bd54>)((vc Git "~/work-stuff/workspace/scripts/"))
  apply(#f(compiled-function (project &optional dirs) #<bytecode 0xf5ba0430963bd54>) (vc Git "~/work-stuff/workspace/scripts/") nil)
  project-files((vc Git "~/work-stuff/workspace/scripts/"))
  pet-find-file-from-project-root-recursively(".pre-commit-config.yaml")
  #f(compiled-function (fn) #<bytecode -0xb857cb2b1613618>)(pet-find-file-from-project-root-recursively)
  #f(compiled-function (elt) #<bytecode 0x865081312aa8510>)(pet-find-file-from-project-root-recursively)
  mapc(#f(compiled-function (elt) #<bytecode 0x865081312aa8510>) (pet-find-file-from-project-root pet-locate-dominating-file pet-find-file-from-project-root-recursively))
  seq-do(#f(compiled-function (elt) #<bytecode 0x865081312aa8510>) (pet-find-file-from-project-root pet-locate-dominating-file pet-find-file-from-project-root-recursively))
  seq-some(#f(compiled-function (fn) #<bytecode -0xb857cb2b1613618>) (pet-find-file-from-project-root pet-locate-dominating-file pet-find-file-from-project-root-recursively))
  pet-find-file-from-project(".pre-commit-config.yaml")
  pet-pre-commit-config-path()
  pet-pre-commit-config()
  pet-use-pre-commit-p()
  pet-executable-find("python")
  pet-buffer-local-vars-setup()
  pet-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-base-mode-hook python-mode-hook)
  apply(run-hooks change-major-mode-after-body-hook (prog-mode-hook python-base-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  python-shell-buffer-substring(1 5164 t nil)
  python-shell-send-region(1 5164 nil t)
  python-shell-send-buffer(nil t)
  funcall-interactively(python-shell-send-buffer nil t)
  command-execute(python-shell-send-buffer)
```

**Comment by wyuenho** [comment]
Does installing projectile solve your problem? The built-in project.el doesn't cache project files after the first search.

**Comment by abougouffa** [comment]
I didn't try, I don't use `projectile`!

**Comment by wyuenho** [comment]
Well, you can just install it, turn on the global mode and forget about it. Just because PET uses it when it's available doesn't mean you have to use it.

Alternatively, you can adjust `pet-find-file-functions`, or propose an improvement to `pet-find-file-from-project-root-recursively`

**Comment by abougouffa** [comment]
FYI: I've just retested it with `projectile` installed, and it still not usable!

I will try to find a hack that works in such cases, I will open a PR if I manage to get it done.

**Comment by abougouffa** [comment]
Hi again @wyuenho 

It seems like the `pet-find-file-from-project-root-recursively` implementation is too heavy. I've overridden it in my config with a simpler function using `fd`, now it is working in the same project almost instantly. Here is my solution:

```elisp
  (defun +pet-find-file-from-project-root-recursively-fd (file)
    (condition-case err
        (when-let* ((root (pet-project-root)))
          (car (cl-remove-if
                #'string-empty-p
                (string-lines (shell-command-to-string (format "fd -t f -H -a -g %S %S" file root))))))
      (error (pet-report-error err))))

  (advice-add 'pet-find-file-from-project-root-recursively :override '+pet-find-file-from-project-root-recursively-fd)
```

I think we can add it to `pet-find-file-from-project-root-recursively` to be used by default when `fd` is present in the system, otherwise, it falls back to the current implementation using `projectile` or `project`. What do you think?

**Comment by wyuenho** [comment]
Doesn't [projectile use fd](https://github.com/bbatsov/projectile/blob/master/projectile.el#L1473) by default when listing files with git anyway? How is your mega directory organized and how many repos are there and how many subdirectories look like a projectile project?

**Comment by abougouffa** [comment]
> Doesn't [projectile use fd](https://github.com/bbatsov/projectile/blob/master/projectile.el#L1473) by default when listing files
It seems to be the case, but in the code above, the `-g` option tells `fd` to perform a search based on a glob pattern, so there's no need to loop on the files in Elisp like it is the cqse in the current implementation.

My codebase is quite simple, but there is a lot of files in a `test/` directory that are used to test the parser. The files are organized in a depth of 3 like `test/X/Y/file1`...

**Comment by wyuenho** [comment]
Ok, sounds good. When you file a PR, see if you can replace the `shell-command-to-string` with just plain old `process-lines`

**Comment by abougouffa** [comment]
@wyuenho Thank you for your patience!

I've opened a PR at #46, please check the PR description for the benchmarks!
